### Approve Request
POST http://localhost:4000/requests/1/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImlxYmFsQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU5MjM2MjUyLCJleHAiOjE3NTkyMzk4NTJ9.f4C3qoQku-9502f_xyBHauLlkOpJTN8AS57hNhz7bgg

### Reject Request
POST http://localhost:4000/requests/1/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImlxYmFsQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU5MjM2MjUyLCJleHAiOjE3NTkyMzk4NTJ9.f4C3qoQku-9502f_xyBHauLlkOpJTN8AS57hNhz7bgg

### Get Incoming Requests (Signer's Inbox)
GET http://localhost:4000/requests/incoming
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImlxYmFsQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU5MjM2MjUyLCJleHAiOjE3NTkyMzk4NTJ9.f4C3qoQku-9502f_xyBHauLlkOpJTN8AS57hNhz7bgg
